### ISSUE TITLE
[Bug Report] type of `onDone` in `MobxInfiniteQuery` is not correct

### ISSUE THREAD

**Issue by ylc395** [js2me/mobx-tanstack-query#5]
https://github.com/js2me/mobx-tanstack-query/blob/8344d0ac40123edf080222f3c4faf3ad8100f105/src/mobx-inifinite-query.types.ts#L114

`TPageParam` is missing. I tried to add it here but this brings more type error.

**Comment by js2me** [comment]
@ylc395 should fixed in `3.3.3`

**Comment by ylc395** [comment]
https://github.com/js2me/mobx-tanstack-query/blob/204db2abd569e3fa4af23937134575b85d6fdea2/src/mobx-inifinite-query.types.ts#L114

Is `TPageParam` still missing here? @js2me

**Comment by js2me** [comment]
@ylc395 thanks, should be fixed in `3.3.5`
